language: node_js
node_js:
  - 12

cache: yarn

install:
  - yarn global add truffle
  - yarn global add ganache@alpha
  - yarn install

script:
  - ganache -e 1000 -a 11 -p 7545 -i 5777 --miner.coinbase 10 --miner.legacyInstamine --miner.blockGasLimit 0x7a1200 > /dev/null &
  - sleep 5
  - yarn compile 
  - yarn mig-ganache
  - yarn test
